export interface RedisInplayFixtureEntity {
  id: string;
  createdAt: number;
  updatedAt: number;
  homeTeamId: string;
  awayTeamId: string;
  start_time: number;
  competitionId: string;
  home_score: number;
  away_score: number;
  state: number;
  status: string;
  first_goal: number;
  win_result: number | null;
  home_score_half: number | null;
  away_score_half: number | null;
  home_score_overtime: number | null;
  away_score_overtime: number | null;
  home_score_penalty: number | null;
  away_score_penalty: number | null;
  first_half_start: number | null;
  second_half_start: number | null;
  minute: number | null;
  minute_string: string | null;
  prematch_odds_fill: number | null;
  prematch_odds_graph_home: number[] | null;
  prematch_odds_graph_away: number[] | null;
  combined_logo_match: string;
  rtp_home_avg: number;
  rtp_away_avg: number;
  xp_home_avg: number;
  xp_away_avg: number;
  next_goal_results: Array<number>;
  best_value_home: number;
  best_value_away: number;
  best_report_minute: number;
  prematch_insights_home_type_1: number;
  prematch_insights_home_header_1: number;
  prematch_insights_home_body_1: number;
  prematch_insights_home_type_2: number;
  prematch_insights_home_header_2: number;
  prematch_insights_home_body_2: number;
  prematch_insights_home_type_3: number;
  prematch_insights_home_header_3: number;
  prematch_insights_home_body_3: number;
  prematch_insights_away_type_1: number;
  prematch_insights_away_header_1: number;
  prematch_insights_away_body_1: number;
  prematch_insights_away_type_2: number;
  prematch_insights_away_header_2: number;
  prematch_insights_away_body_2: number;
  prematch_insights_away_type_3: number;
  prematch_insights_away_header_3: number;
  prematch_insights_away_body_3: number;
  results_home_win: Array<number>;
  results_home_handicap: Array<number>;
  results_home_total: Array<number>;
  results_home_goal: Array<number>;
  results_home_btts: Array<number>;
  results_home_handicap_first: Array<number>;
  results_home_handicap_second: Array<number>;
  results_home_indiv_total: Array<number>;
  results_home_indiv_total_opp: Array<number>;
  odds_home_win: Array<number>;
  odds_home_handicap: Array<number>;
  odds_home_total: Array<number>;
  odds_home_goal: Array<number>;
  odds_home_handicap_first: Array<number>;
  odds_home_handicap_second: Array<number>;
  odds_home_indiv_total: Array<number>;
  odds_home_indiv_total_opp: Array<number>;
  summary_home_win: number;
  summary_home_handicap: number;
  summary_home_total: number;
  summary_home_goal: number;
  summary_home_btts: number;
  summary_home_handicap_first: number;
  summary_home_handicap_second: number;
  summary_home_indiv_total: number;
  summary_home_indiv_total_opp: number;
  last_ten_rtp_home: Array<number>;
  last_ten_rta_home: Array<number>;
  last_ten_dang_att_home: Array<number>;
  last_ten_shots_home: Array<number>;
  last_ten_shots_on_home: Array<number>;
  last_ten_shots_off_home: Array<number>;
  last_ten_xpg_home: Array<number>;
  summary_last_ten_rtp_home: number;
  summary_last_ten_rta_home: number;
  summary_last_ten_dang_att_home: number;
  summary_last_ten_shots_home: number;
  summary_last_ten_shots_on_home: number;
  summary_last_ten_shots_off_home: number;
  summary_last_ten_xpg_home: number;
  results_away_win: Array<number>;
  results_away_handicap: Array<number>;
  results_away_total: Array<number>;
  results_away_goal: Array<number>;
  results_away_btts: Array<number>;
  results_away_handicap_first: Array<number>;
  results_away_handicap_second: Array<number>;
  results_away_indiv_total: Array<number>;
  results_away_indiv_total_opp: Array<number>;
  odds_away_win: Array<number>;
  odds_away_handicap: Array<number>;
  odds_away_total: Array<number>;
  odds_away_goal: Array<number>;
  odds_away_btts: Array<number>;
  odds_away_handicap_first: Array<number>;
  odds_away_handicap_second: Array<number>;
  odds_away_indiv_total: Array<number>;
  odds_away_indiv_total_opp: [17.2];
  summary_away_win: number;
  summary_away_handicap: number;
  summary_away_total: number;
  summary_away_goal: number;
  summary_away_btts: number;
  summary_away_handicap_first: number;
  summary_away_handicap_second: number;
  summary_away_indiv_total: number;
  summary_away_indiv_total_opp: number;
  last_ten_rtp_away: Array<number>;
  last_ten_rta_away: Array<number>;
  last_ten_dang_att_away: Array<number>;
  last_ten_shots_away: Array<number>;
  last_ten_shots_on_away: Array<number>;
  last_ten_shots_off_away: Array<number>;
  last_ten_xpg_away: Array<number>;
  summary_last_ten_rtp_away: number;
  summary_last_ten_rta_away: number;
  summary_last_ten_dang_att_away: number;
  summary_last_ten_shots_away: number;
  summary_last_ten_shots_on_away: number;
  summary_last_ten_shots_off_away: number;
  summary_last_ten_xpg_away: number;
  favorites_count: number | null;
}
