export interface RedisInplayMainIsportEntity {
  fixture_id: string;
  createdAt: number;
  updatedAt: number;
  minute: number;
  asian_away_cf: number;
  asian_home_cf: number;
  asian_away: number;
  asian_home: number;
  odd_win_home: number;
  odd_win_away: number;
  odd_draw: number;
  coeff_bk: number;
  dang_att_home_stats: number;
  dang_att_away_stats: number;
  away_goal: number;
  home_goal: number;
  goal_total: number;
  goal_under: number;
  goal_over: number;
  goal_status: number;
  ai_insight_top: number | null;
  ai_insight_total: number | null;
  asian_home_cf_dynamic: number | null;
  asian_away_cf_dynamic: number | null;
  goal_under_dynamic: number | null;
  goal_over_dynamic: number | null;
  odd_win_home_dynamic: number | null;
  odd_draw_dynamic: number | null;
  odd_win_away_dynamic: number | null;
  similar_match_id_1: string | null;
  similar_match_id_2: string | null;
  similar_match_id_3: string | null;
  live_insights_home_type_1: number | null;
  live_insights_home_header_1: number | null;
  live_insights_home_body_1: number | null;
  live_insights_home_type_2: number | null;
  live_insights_home_header_2: number | null;
  live_insights_home_body_2: number | null;
  live_insights_home_type_3: number | null;
  live_insights_home_header_3: number | null;
  live_insights_home_body_3: number | null;
  live_insights_home_type_4: number | null;
  live_insights_home_header_4: number | null;
  live_insights_home_body_4: number | null;
  live_insights_home_type_5: number | null;
  live_insights_home_header_5: number | null;
  live_insights_home_body_5: number | null;
  live_insights_home_type_6: number | null;
  live_insights_home_header_6: number | null;
  live_insights_home_body_6: number | null;
  live_insights_away_type_1: number | null;
  live_insights_away_header_1: number | null;
  live_insights_away_body_1: number | null;
  live_insights_away_type_2: number | null;
  live_insights_away_header_2: number | null;
  live_insights_away_body_2: number | null;
  live_insights_away_type_3: number | null;
  live_insights_away_header_3: number | null;
  live_insights_away_body_3: number | null;
  live_insights_away_type_4: number | null;
  live_insights_away_header_4: number | null;
  live_insights_away_body_4: number | null;
  live_insights_away_type_5: number | null;
  live_insights_away_header_5: number | null;
  live_insights_away_body_5: number | null;
  live_insights_away_type_6: number | null;
  live_insights_away_header_6: number | null;
  live_insights_away_body_6: number | null;
  odds_goal_home: number | null;
  odds_goal_away: number | null;
  odds_goal_nobody: number | null;
  odds_scores_1: number | null;
  odds_scores_2: number | null;
  odds_scores_3: number | null;
  odds_scores_4: number | null;
  odds_scores_5: number | null;
  odds_scores_6: number | null;
  outcomes_win_home: number | null;
  outcomes_win_home_adv: number | null;
  outcomes_win_home_odds: number | null;
  outcomes_win_draw: number | null;
  outcomes_win_draw_adv: number | null;
  outcomes_win_draw_odds: number | null;
  outcomes_win_away: number | null;
  outcomes_win_away_adv: number | null;
  outcomes_win_away_odds: number | null;
  outcomes_handicap_home: number | null;
  outcomes_handicap_home_adv: number | null;
  outcomes_handicap_home_odds: number | null;
  outcomes_handicap_away: number | null;
  outcomes_handicap_away_adv: number | null;
  outcomes_handicap_away_odds: number | null;
  outcomes_total_over: number | null;
  outcomes_total_over_adv: number | null;
  outcomes_total_over_odds: number | null;
  outcomes_total_under: number | null;
  outcomes_total_under_adv: number | null;
  outcomes_total_under_odds: number | null;
  outcomes_goal_home: number | null;
  outcomes_goal_home_adv: number | null;
  outcomes_goal_home_odds: number | null;
  outcomes_goal_away: number | null;
  outcomes_goal_away_adv: number | null;
  outcomes_goal_away_odds: number | null;
  outcomes_goal_nobody: number | null;
  outcomes_goal_nobody_adv: number | null;
  outcomes_goal_nobody_odds: number | null;
  match_scores_1: string | null;
  match_scores_2: string | null;
  match_scores_3: string | null;
  match_scores_4: string | null;
  match_scores_5: string | null;
  match_scores_6: string | null;
  outcomes_scores_1: number | null;
  outcomes_scores_2: number | null;
  outcomes_scores_3: number | null;
  outcomes_scores_4: number | null;
  outcomes_scores_5: number | null;
  outcomes_scores_6: number | null;
  outcomes_scores_adv_1: number | null;
  outcomes_scores_adv_2: number | null;
  outcomes_scores_adv_3: number | null;
  outcomes_scores_adv_4: number | null;
  outcomes_scores_adv_5: number | null;
  outcomes_scores_adv_6: number | null;
  outcomes_scores_odds_1: number | null;
  outcomes_scores_odds_2: number | null;
  outcomes_scores_odds_3: number | null;
  outcomes_scores_odds_4: number | null;
  outcomes_scores_odds_5: number | null;
  outcomes_scores_odds_6: number | null;
  match_uniqueness_home: number | null;
  match_uniqueness_away: number | null;
  realtime_graph_rtp_home: Array<number> | null;
  realtime_graph_rtp_away: Array<number> | null;
  realtime_graph_xp_home: Array<number> | null;
  realtime_graph_xp_away: Array<number> | null;
  predictive_graph_rtp_home: Array<number> | null;
  predictive_graph_rtp_away: Array<number> | null;
  predictive_graph_xp_home: Array<number> | null;
  predictive_graph_xp_away: Array<number> | null;
  exp_power_growth_home: number | null;
  exp_power_growth_away: number | null;
  coeff_live_dynamics: number | null;
  cf_live_2nd_dynamics: number | null;
  coeff_bk_new_dynamics: number | null;
  coeff_bk_new_2_dynamics: number | null;
  cf_live_difference_new_dynamics: number | null;
  odds_graph_home: Array<number> | null;
  odds_graph_away: Array<number> | null;
  draw_no_bet_cf_1st: number | null;
  draw_no_bet_cf_2nd: number | null;
  draw_no_bet_1st_perc: number | null;
  draw_no_bet_2nd_perc: number | null;
  coeff_live: number | null;
  cf_live_2nd: number | null;
  cf_live_difference: number | null;
  bet_team: number | null;
  indicator_type: number | null;
  indicator_reason: number | null;
  cf_live_difference_new: number | null;
  cf_live_difference_avg: number | null;
  coeff_bk_new_2: number | null;
  coeff_bk_new: number | null;
  outcomes_win_home_count_1: number | null;
  outcomes_win_home_count_2: number | null;
  outcomes_win_draw_count_1: number | null;
  outcomes_win_draw_count_2: number | null;
  outcomes_win_away_count_1: number | null;
  outcomes_win_away_count_2: number | null;
  outcomes_handicap_home_count_1: number | null;
  outcomes_handicap_home_count_2: number | null;
  outcomes_handicap_away_count_1: number | null;
  outcomes_handicap_away_count_2: number | null;
  outcomes_total_over_count_1: number | null;
  outcomes_total_over_count_2: number | null;
  outcomes_total_under_count_1: number | null;
  outcomes_total_under_count_2: number | null;
  outcomes_goal_home_count_1: number | null;
  outcomes_goal_home_count_2: number | null;
  outcomes_goal_away_count_1: number | null;
  outcomes_goal_away_count_2: number | null;
  outcomes_goal_nobody_count_1: number | null;
  outcomes_goal_nobody_count_2: number | null;
  outcomes_scores_1_count_1: number | null;
  outcomes_scores_1_count_2: number | null;
  outcomes_scores_2_count_1: number | null;
  outcomes_scores_2_count_2: number | null;
  outcomes_scores_3_count_1: number | null;
  outcomes_scores_3_count_2: number | null;
  outcomes_scores_4_count_1: number | null;
  outcomes_scores_4_count_2: number | null;
  outcomes_scores_5_count_1: number | null;
  outcomes_scores_5_count_2: number | null;
  outcomes_scores_6_count_1: number | null;
  outcomes_scores_6_count_2: number | null;
  outcomes_handicap_void_count_1: number | null;
  outcomes_handicap_void_count_2: number | null;
  outcomes_handicap_void: number | null;
  outcomes_total_void_count_1: number | null;
  outcomes_total_void_count_2: number | null;
  outcomes_total_void: number | null;
  rtpi_number_1_home: number | null;
  rtpi_number_2_home: number | null;
  rtpi_number_1_away: number | null;
  rtpi_number_2_away: number | null;
}
